---
version: "2.0"

services:
  miyu-data:
    image: arealicehole/miyu-data:MDB2A
    env:
      # Discord Configuration (REQUIRED)
      - DISCORD_TOKEN=
      
      # AI Provider Configuration (REQUIRED)
      - AI_PROVIDER=openrouter
      - OPENROUTER_API_KEY=
      - OPENROUTER_MODEL=openai/gpt-4o-mini
      - APP_NAME=Miyu-Data Discord Bot
      
      # Embeddings Configuration for RAG (REQUIRED)
      - OPENAI_API_KEY=
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_PROVIDER=openai
      
      # Pinecone Vector Database (REQUIRED)
      - PINECONE_API_KEY=
      - PINECONE_INDEX=miyu-testa
      - PINECONE_DIMENSION=3072
      - PINECONE_CLOUD=aws
      - PINECONE_REGION=us-east-1
      
      # Performance Configuration
      - YOLO_MODE=false
      - RAG_CHUNK_SIZE=1500
      - RAG_CHUNK_OVERLAP=200
      - MAX_TOKENS=4096
      - TEMPERATURE=0.7
      
      # Conversation Settings
      - CONVERSATION_HISTORY_LIMIT=10
      - CONVERSATION_TIMEOUT_MINUTES=30
      
      # Query Optimization
      - QUERY_TOP_K=5
      - SIMILARITY_THRESHOLD=0.3
      
      # Python Runtime
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    # No exposed ports needed for Discord bot
    expose:
      - port: 8080
        as: 80
        accept:
          - miyu-health
        to:
          - global: false

profiles:
  compute:
    miyu-data:
      resources:
        cpu:
          units: 1.0          # 1 CPU core for processing
        memory:
          size: 1Gi           # 1GB RAM for bot + caching
        storage:
          size: 2Gi           # Storage for logs/temp files
  
  placement:
    westcoast:
      attributes:
        region: us-west
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"  # Akash Network
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"  # Praetor
      pricing:
        miyu-data:
          denom: uakt
          amount: 100         # ~0.0001 AKT per block

deployment:
  miyu-data:
    westcoast:
      profile: miyu-data
      count: 1