---
version: "2.0"

services:
  web:
    image: arealicehole/miyu-data:MDB2A
    env:
      - DISCORD_TOKEN=
      - AI_PROVIDER=openrouter
      - OPENROUTER_API_KEY=
      - OPENROUTER_MODEL=openai/gpt-4o-mini
      - OPENAI_API_KEY=
      - PINECONE_API_KEY=
      - PINECONE_INDEX=miyu-testa
      - PYTHONUNBUFFERED=1
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi
  
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1